package common

var SUCCESS = 0
var SUCCESS_MSG = "ok"

var E_IO_INVALID_LINK_ID = 1
var E_IO_INVALID_BOX_ID = 2
var E_IO_DECODE_BOX = 3
var E_IO_DECODE_LINK = 4
var E_IO_AUTH_PARSE = 5
var E_IO_TOKEN_CREATION = 6
var E_IO_INVALID_LOGIN = 7

var E_DB_BOX_NOT_FOUND = 100
var E_DB_LINK_NOT_FOUND = 101
var E_DB_CREATE_BOX = 102
var E_DB_CREATE_LINK = 103
var E_DB_UPDATE_BOX = 104
var E_DB_UPDATE_LINK = 105
